image: golang:1.20

variables:
  # Define your environment variables here
  IP2LOCATION_PATH: "static/IP2LOCATION-LITE-DB5.BIN"

before_script:
  - go get -v -d ./...  


stages:
  - unit_test
  # - integration_test

unit:
  stage: unit_test
  script:
    - go test -v ./...
  tags:
    - unit_test

# integration:
#   stage: integration_test
#   script:
#     - go test -v ./... -tags=integration