Redis:
  HOSTNAME: redis.local
  PORT: 6379

Rabbitmq:
  RABBITMQ_HOSTNAME: rabbitmq.local
  RABBITMQ_USERNAME: root
  RABBITMQ_PASSWORD: 123
  RABBITMQ_PORT: 5672
  RABBITMQ_WEB_PORT: 15672

MARIADB:
  MARIADB_DATABASE: edetector
  MARIADB_USER: edetector
  MARIADB_PASSWORD: edetector123
  MARIADB_ROOT_PASSWORD: root123
  MARIADB_HOSTNAME: mariadb.local
  MARIADB_PORT: 3306

pywebsite:
  PYWEBSITE_HOSTNAME: pywebsite.local
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: 8000
  FLASK_API_TOKEN: ciDeUDL5J3lYlue5qUcIlmO3o1Y1OkybWdohts8Err0q5ROgy2IwdW1sg5bLKeTefpYR2DqCugiveJC4K5YLiXnJe1iXN2SCOItOBwnsn2RP4e3B282uSwcD3Jw3ylE8
  SECRET_KEY: 2b2c5a243c2be6f0e3782e4e6408a610

ELASTIC:
  ELASTIC_HOST: 192.168.50.143
  ELASTIC_PORT: 9200

pysearch:
  PYSEARCH_HOSTNAME: pysearch.local
  PYSEARCH_HOST: 0.0.0.0
  PYSEARCH_PORT: 2016
  PYSEARCH_AESKEY: AES Encrypt Decrypt

goworker:
  PYWORKER_HOSTNAME: pyworker.local
  PYWORKER_HOST: 0.0.0.0
  DEBUG_PORT: 5678
  DEFAULT_WORKER_PORT: 1988
  DEFAULT_DETECT_PORT: 1989
  SERVER_TYPE_TCP: tcp
  SERVER_TYPE_UDP: udp
  LOG_FILE: /var/log/pyworker.log